version: '3' #tror det er denne som skal inkremeneteres som en id
services:
  db:
    image: postgres:latest
    hostname: "Postgres"
    expose:
      - 5432
    restart: always
    environment:
      POSTGRES_USER: "postgres"  
      POSTGRES_PASSWORD: "devops"   
      POSTGRES_DB: "newdb"  # Navn på db
    volumes:
      - tmp-db:/var/lib/postgresql/data/
      - ./database.sql:/docker-entrypoint-init.d/database.sql
    networks:
      - PostgresNetwork
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8090"
    restart: always

    networks:
      - PostgresNetwork

networks:
   PostgresNetwork:
    driver: bridge

volumes:
   tmp-db:
